// <auto-generated />
namespace Sample.Migrations.SampleDomainContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_BornInfo_on_Person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_BornInfo_on_Person));
        
        string IMigrationMetadata.Id
        {
            get { return "201505190842154_Add_BornInfo_on_Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
