// <auto-generated />
namespace Sample.Migrations.SampleDomainContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_RowVersion_Column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_RowVersion_Column));
        
        string IMigrationMetadata.Id
        {
            get { return "201505261357091_Change_RowVersion_Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
