// <auto-generated />
namespace Sample.Migrations.SampleDomainContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DomainEventCommit_is_dispatched_and_stream_group : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DomainEventCommit_is_dispatched_and_stream_group));
        
        string IMigrationMetadata.Id
        {
            get { return "201507141117147_DomainEventCommit_is_dispatched_and_stream_group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
